# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo_notification' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo_notification

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'demo_notificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'demo_notification-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for demo_notification-tvOS

  target 'demo_notification-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

